path: path/to/images  # path to images (relative to the parent directory)
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: a