theme = "hugo-book"
baseURL = 'https://opencivi.io/'
languageCode = 'en-us'
title = 'OpenCivi'

disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[languages.es]
  languageName = 'Español'
  contentDir = 'content.es'
  weight = 2

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/sergioarmgpl/opencivi"
  weight = 10

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookLogo = 'logo2.png'
